Senayan3: detail::showDetail
$detail_id
$detail_prefix
$detail_suffix
$error
$metadata
$obj_db
$output_format
$record_detail
$record_title
__construct
getPrefix
getSuffix
htmlOutput
MODSoutput
showDetail
showDetail ()
Method to print out the document detail based on template
Returns:
void
Definition at line 88 of file detail.inc.php.
References htmlOutput(), MODSoutput(), and content_list::parseListTemplate().