Senayan3: $scale
$code
$encoding
$mode
$scale
$scale = trim($_GET['scale'])
Definition at line 38 of file barcode.php.
Referenced by phpthumb::ApplyFilters(), barcode_outimage(), barcode_print(), and phpthumb_functions::ScaleToFitInBox().