Senayan3: RedirectToCachedFile
$allowedGETparameters
$CanPassThroughDirectly
$parsed_url_referer
$parsed_url_src
$phpThumb
$PHPTHUMB_DEFAULTS_DISABLEGETPARAMS
$starttime
RedirectToCachedFile
SendSaveAsFileHeaderIfNeeded
if (@$_GET['phpThumbDebug']== '5') RedirectToCachedFile ()
Definition at line 415 of file phpThumb.php.
References $phpThumb, $PHPTHUMB_CONFIG, exit, phpthumb_functions::ImageTypeToMIMEtype(), phpthumb_functions::ParseURLbetter(), and SendSaveAsFileHeaderIfNeeded().