Senayan3: circulation::extendItemLoan
$fine_each_day
$grace_periode
$holiday_date
$holiday_dayname
$item_loan_rules
$loan_have_overdue
$loan_limit
$loan_periode
$overdue_days
$reborrow_limit
__construct
addLoanSession
countOverdueValue
extendItemLoan
finishLoanSession
getOverdueDays
removeLoanSession
returnItem
setLoanRules
extendItemLoan ($ int_loan_id)
extend item loan
Parameters:
integer $int_loan_id
Returns:
integer/boolean
Definition at line 279 of file circulation_base_lib.inc.php.
References $query, simbio_date::getNextDate(), simbio_date::getNextDateNotHoliday(), and returnItem().