Senayan3: phpUnsharpMask::applyUnsharpMask
applyUnsharpMask
applyUnsharpMask (&$ img, $ amount, $ radius, $ threshold)
Definition at line 42 of file phpthumb.unsharp.php.
References phpthumb_functions::gd_is_bundled(), and phpthumb_functions::version_compare_replacement().
Referenced by phpthumb::ApplyFilters().