Senayan3: simbio_form_table_AJAX::printOut
$back_button
$delete_button
$edit_mode
$record_id
$record_title
$submit_button_attr
$table_attr
$table_content_attr
$table_header_attr
$with_form_tag
__construct
printOut
printOut ()
Method to printOut form object
Reimplemented from simbio_form_maker.
Definition at line 56 of file simbio_form_table_AJAX.inc.php.
References $row, __(), simbio_form_maker::endForm(), simbio_form_maker::startForm(), submit_button_attr, table_attr, table_content_attr, and table_header_attr.