Senayan3: serial::viewKardexes
$biblio_id
$frequency_increment
$frequency_time_unit
$obj_db
$serial_date_start
$serial_id
$serial_period
__construct
deleteKardex
generateKardexes
getKardexes
saveKardexes
viewKardexes
viewKardexes ()
View kardex list
Returns:
string
Definition at line 123 of file serial_base_lib.inc.php.
References __(), simbio_form_element::dateField(), getKardexes(), utility::havePrivilege(), simbio_form_element::hiddenField(), and simbio_form_element::textField().