Senayan3: simbio_date::getNextDate
calcDay
compareDates
countHolidayBetween
getNextDate
getNextDateNotHoliday
getPrevDate
static getNextDate ($ int_day_num = 1, $ str_start_date = '', $ str_date_format = 'Y-m-d') [static]
Static Method to get next date
Parameters:
integer $int_day_num
string $str_start_date
string $str_start_format
Returns:
string
Definition at line 41 of file simbio_date.inc.php.
Referenced by circulation::addLoanSession(), circulation::countOverdueValue(), circulation::extendItemLoan(), and getNextDateNotHoliday().