Senayan3: simbio_date::getNextDateNotHoliday
calcDay
compareDates
countHolidayBetween
getNextDate
getNextDateNotHoliday
getPrevDate
static getNextDateNotHoliday ($ str_date, $ array_holiday_dayname = array(), $ array_holiday_date = array()) [static]
Static Method to get next date that are not holidays
Parameters:
string $str_date
array $array_holiday_dayname
array $array_holiday_date
Returns:
string
Definition at line 169 of file simbio_date.inc.php.
References getNextDate().
Referenced by circulation::addLoanSession(), and circulation::extendItemLoan().