Senayan3: simbio_date::compareDates
calcDay
compareDates
countHolidayBetween
getNextDate
getNextDateNotHoliday
getPrevDate
static compareDates () [static]
Static Method to compare dates and return the latest date
Parameters:
string $str_date_to_compares
Returns:
string
Definition at line 127 of file simbio_date.inc.php.
Referenced by member::__construct(), circulation::addLoanSession(), circulation::countOverdueValue(), and member_logon::valid().