Senayan3: phpthumb_bmp::getid3_bmp
BigEndian2Bin
BigEndian2Int
Bin2Dec
BMPcompressionOS2Lookup
BMPcompressionWindowsLookup
CastAsInt
FixedPoint2_30
GD2BMPstring
getid3_bmp
IntColor2RGB
LittleEndian2Int
phpthumb_bmp
phpthumb_bmp2gd
phpthumb_bmpfile2gd
PlotBMP
PlotPixelsGD
trunc
getid3_bmp (&$ BMPdata, &$ ThisFileInfo, $ ExtractPalette = false, $ ExtractData = false)
Definition at line 86 of file phpthumb.bmp.php.
References $row, BMPcompressionOS2Lookup(), BMPcompressionWindowsLookup(), FixedPoint2_30(), and LittleEndian2Int().
Referenced by phpthumb_bmp2gd().