Senayan3: phpthumb_filters::ApplyMask
$phpThumbObject
ApplyMask
Bevel
Blur
BlurGaussian
BlurSelective
Brightness
Colorize
Contrast
Crop
DebugMessage
Desaturate
DropShadow
EdgeDetect
Elipse
Emboss
Flip
Frame
Gamma
Grayscale
HistogramAnalysis
HistogramOverlay
HistogramStretch
ImageBorder
ImageTrueColorToPalette2
ImprovedImageRotate
MeanRemoval
Negative
phpthumb_filters
ReduceColorDepth
RoundedImageCorners
Saturation
Sepia
Smooth
SourceTransparentColorMask
Threshold
WatermarkOverlay
WatermarkText
WhiteBalance
ApplyMask (&$ gdimg_mask, &$ gdimg_image)
Definition at line 19 of file phpthumb.filters.php.
References DebugMessage(), phpthumb_functions::gd_version(), phpthumb_functions::GetPixelColor(), phpthumb_functions::GrayscalePixel(), phpthumb_functions::ImageColorAllocateAlphaSafe(), phpthumb_functions::ImageCreateFunction(), and phpthumb_functions::version_compare_replacement().
Referenced by Elipse(), RoundedImageCorners(), and WatermarkText().