Senayan3: phpthumb_filters::WatermarkText
$phpThumbObject
ApplyMask
Bevel
Blur
BlurGaussian
BlurSelective
Brightness
Colorize
Contrast
Crop
DebugMessage
Desaturate
DropShadow
EdgeDetect
Elipse
Emboss
Flip
Frame
Gamma
Grayscale
HistogramAnalysis
HistogramOverlay
HistogramStretch
ImageBorder
ImageTrueColorToPalette2
ImprovedImageRotate
MeanRemoval
Negative
phpthumb_filters
ReduceColorDepth
RoundedImageCorners
Saturation
Sepia
Smooth
SourceTransparentColorMask
Threshold
WatermarkOverlay
WatermarkText
WhiteBalance
WatermarkText (&$ gdimg, $ text, $ size, $ alignment, $ hex_color = '000000', $ ttffont = '', $ opacity = 100, $ margin = 5, $ angle = 0, $ bg_color = false, $ bg_opacity = 0, $ fillextend = '')
Definition at line 1091 of file phpthumb.filters.php.
References $bg_color, ApplyMask(), DebugMessage(), phpthumb_functions::ImageCreateFunction(), phpthumb_functions::ImageHexColorAllocate(), phpthumb_functions::IsHexColor(), and WatermarkOverlay().