Senayan3: phpthumb_filters::Negative
$phpThumbObject
ApplyMask
Bevel
Blur
BlurGaussian
BlurSelective
Brightness
Colorize
Contrast
Crop
DebugMessage
Desaturate
DropShadow
EdgeDetect
Elipse
Emboss
Flip
Frame
Gamma
Grayscale
HistogramAnalysis
HistogramOverlay
HistogramStretch
ImageBorder
ImageTrueColorToPalette2
ImprovedImageRotate
MeanRemoval
Negative
phpthumb_filters
ReduceColorDepth
RoundedImageCorners
Saturation
Sepia
Smooth
SourceTransparentColorMask
Threshold
WatermarkOverlay
WatermarkText
WhiteBalance
Negative (&$ gdimg)
Definition at line 846 of file phpthumb.filters.php.
References DebugMessage(), phpthumb_functions::gd_is_bundled(), phpthumb_functions::GetPixelColor(), phpthumb_functions::ImageColorAllocateAlphaSafe(), and phpthumb_functions::version_compare_replacement().