Senayan3: phpthumb::ImageCreateFromFilename
$allow_local_http_src
$AlphaCapableFormats
$aoe
$ar
$bc
$bg
$cache_filename
$config_allow_parameter_file
$config_allow_parameter_goto
$config_allow_src_above_docroot
$config_allow_src_above_phpthumb
$config_background_hexcolor
$config_border_hexcolor
$config_cache_default_only_suffix
$config_cache_directory
$config_cache_directory_depth
$config_cache_disable_warning
$config_cache_force_passthru
$config_cache_maxage
$config_cache_maxfiles
$config_cache_maxsize
$config_cache_prefix
$config_cache_source_directory
$config_cache_source_enabled
$config_cache_source_filemtime_ignore_local
$config_cache_source_filemtime_ignore_remote
$config_disable_debug
$config_disable_imagecopyresampled
$config_disable_onlycreateable_passthru
$config_disable_pathinfo_parsing
$config_document_root
$config_error_bgcolor
$config_error_die_on_error
$config_error_die_on_source_failure
$config_error_fontsize
$config_error_image_height
$config_error_image_width
$config_error_message_image_default
$config_error_silent_die_on_error
$config_error_textcolor
$config_high_security_enabled
$config_high_security_password
$config_http_follow_redirect
$config_http_fopen_timeout
$config_http_user_agent
$config_imagemagick_path
$config_imagemagick_use_thumbnail
$config_max_source_pixels
$config_mysql_database
$config_mysql_hostname
$config_mysql_password
$config_mysql_query
$config_mysql_username
$config_nohotlink_enabled
$config_nohotlink_erase_image
$config_nohotlink_text_message
$config_nohotlink_valid_domains
$config_nooffsitelink_enabled
$config_nooffsitelink_erase_image
$config_nooffsitelink_require_refer
$config_nooffsitelink_text_message
$config_nooffsitelink_valid_domains
$config_nooffsitelink_watermark_src
$config_output_format
$config_output_interlace
$config_output_maxheight
$config_output_maxwidth
$config_prefer_imagemagick
$config_temp_directory
$config_ttf_directory
$config_use_exif_thumbnail_for_speed
$debugmessages
$debugtiming
$down
$dpi
$err
$exif_raw_data
$exif_thumbnail_data
$exif_thumbnail_height
$exif_thumbnail_type
$exif_thumbnail_width
$f
$far
$fatalerror
$file
$fltr
$gdimg_output
$gdimg_source
$getimagesizeinfo
$goto
$h
$hl
$hp
$hs
$iar
$IMresizedData
$is_alpha
$iswindows
$maxb
$md5s
$new
$outputImageData
$phpthumb_version
$phpThumbDebug
$q
$ra
$rawImageData
$sfn
$sh
$sia
$source_height
$source_width
$sourceFilename
$src
$sw
$sx
$sy
$thumbnail_height
$thumbnail_image_height
$thumbnail_image_width
$thumbnail_width
$thumbnailCropH
$thumbnailCropW
$thumbnailCropX
$thumbnailCropY
$thumbnailFormat
$thumbnailQuality
$useRawIMoutput
$w
$wl
$wp
$ws
$xto
$zc
AlphaChannelFlatten
AntiOffsiteLinking
ApplyFilters
CalculateThumbnailDimensions
CleanUpCacheDirectory
CreateGDoutput
DebugMessage
DebugTimingMessage
ErrorImage
ExtractEXIFgetImageSize
FatalError
FixedAspectRatio
GenerateThumbnail
getParameter
ImageCreateFromFilename
ImageCreateFromStringReplacement
ImageMagickCommandlineBase
ImageMagickFormatsList
ImageMagickSwitchAvailable
ImageMagickThumbnailToGD
ImageMagickVersion
ImageMagickWhichConvert
ImageResizeFunction
InitializeTempDirSetting
MaxFileSize
OffsiteDomainIsAllowed
OutputThumbnail
phpThumb
phpThumb_tempnam
phpThumbDebug
phpThumbDebugVarDump
RenderOutput
RenderToFile
resetObject
ResolveFilenameToAbsolute
ResolveSource
Rotate
setCacheDirectory
SetCacheFilename
SetOrientationDependantWidthHeight
setOutputFormat
setParameter
setSourceData
setSourceFilename
setSourceImageResource
SourceDataToTempFile
SourceImageIsTooLarge
SourceImageToGD
ImageCreateFromFilename ($ filename)
Definition at line 3182 of file phpthumb.class.php.
References $getimagesizeinfo, DebugMessage(), ImageCreateFromStringReplacement(), and SourceImageIsTooLarge().
Referenced by ApplyFilters(), and SourceImageToGD().