Senayan3: report_datagrid::makeOutput
$paging_set
$using_AJAX
__construct
makeOutput
makeOutput ($ int_num2show = 30) [protected]
Modified method to make HTML output more friendly to printer
Parameters:
object $obj_db
integer $int_num2show
Returns:
string
Reimplemented from simbio_datagrid.
Definition at line 44 of file report_dbgrid.inc.php.
References __(), simbio_table::appendTableRow(), column_width, simbio_paging::paging(), simbio_table::printTable(), simbio_datagrid::removeInvisibleField(), simbio_table::setCellAttr(), and simbio_table::setHeader().