Senayan3: gif_loadFileToGDimageResource
gif_getSize
gif_loadFile
gif_loadFileToGDimageResource
gif_outputAsBmp
gif_outputAsJpeg
gif_outputAsPng
gif_loadFileToGDimageResource ($ gifFilename, $ bgColor = -1)
Definition at line 36 of file phpthumb.gif.php.
References phpthumb_functions::FunctionIsDisabled(), and gif_loadFile().
Referenced by phpthumb::ImageCreateFromStringReplacement().