Senayan3: _encode
$CURRENTLOCALE
$default_domain
$EMULATEGETTEXT
$LC_CATEGORIES
$text_domains
__
_bind_textdomain_codeset
_bindtextdomain
_check_locale
_dcgettext
_dcngettext
_dgettext
_dngettext
_encode
_get_codeset
_get_reader
_gettext
_ngettext
_setlocale
_textdomain
locale_emulation
T_
T_bind_textdomain_codeset
T_bindtextdomain
T_dcgettext
T_dcngettext
T_dgettext
T_dngettext
T_gettext
T_ngettext
T_setlocale
T_textdomain
_encode ($ text)
Convert the given string to the encoding set by bind_textdomain_codeset.
Definition at line 104 of file gettext.inc.
References _get_codeset().
Referenced by _dcgettext(), _dcngettext(), _dgettext(), _dngettext(), _gettext(), and _ngettext().