Senayan3: $timeout
$curr_timestamp
$timeout
$unauthorized
$timeout = ($curr_timestamp-$_SESSION['logintime']) >= $sysconf['session_timeout']
Definition at line 51 of file session_check.inc.php.
Referenced by phpthumb_functions::filedate_remote(), phpthumb_functions::filesize_remote(), phpthumb_functions::SafeURLread(), and phpthumb_functions::URLreadFsock().