Senayan3: barcode_encode
$bar_color
$bg_color
$font_loc
$text_color
barcode_encode
barcode_encode_genbarcode
barcode_outimage
barcode_print
ENCODING_UNHANDLED
GD_NOT_LOADED
barcode_encode ($ code, $ encoding)
Encodes $code with $encoding using genbarcode OR built-in encoder if you don't have genbarcode only EAN-13/ISBN is possible
You can use the following encodings (when you have genbarcode): ANY choose best-fit (default) EAN 8 or 13 EAN-Code UPC 12-digit EAN ISBN isbn numbers (still EAN-13) 39 code 39 128 code 128 (a,b,c: autoselection) 128C code 128 (compact form for digits) 128B code 128, full printable ascii I25 interleaved 2 of 5 (only digits) 128RAW Raw code 128 (by Leonid A. Broukhis) CBR Codabar (by Leonid A. Broukhis) MSI MSI (by Leonid A. Broukhis) PLS Plessey (by Leonid A. Broukhis)
Parameters:
mixed $code
mixed $encoding
Returns:
array[encoding] : the encoding which has been used
array[bars] : the bars
array[text] : text-positioning info
Definition at line 245 of file php-barcode.php.
References $code, $encoding, barcode_encode_ean(), and barcode_encode_genbarcode().
Referenced by barcode_print().