Senayan3: simbio::showError
$error
$version
colorSQLstring
showError
showError ($ bool_die = false)
Method to show an error
Parameters:
boolean $bool_die
Returns:
void
Definition at line 40 of file simbio.inc.php.
Referenced by simbio_sqlite::connect(), simbio_pgsql::connect(), simbio_mysql::connect(), simbio_isis::connect(), simbio_sqlite::query(), simbio_pgsql::query(), simbio_mysql::query(), and simbio_isis::query().