Senayan3: phpthumb_functions::gd_is_bundled
ApacheLookupURIarray
builtin_function_exists
CaseInsensitiveInArray
CleanUpURLencoding
EnsureDirectoryExists
exif_info
filedate_remote
filesize_remote
FunctionIsDisabled
gd_is_bundled
gd_version
GetAllFilesInSubfolders
GetPixelColor
GrayscalePixel
GrayscalePixelRGB
GrayscaleValue
HexCharDisplay
HexColorXOR
ImageColorAllocateAlphaSafe
ImageCopyResampleBicubic
ImageCopyRespectAlpha
ImageCreateFunction
ImageHexColorAllocate
ImageTypeToMIMEtype
IsHexColor
LittleEndian2String
md5_file_safe
nonempty_min
OneOfThese
ParseURLbetter
phpinfo_array
PixelColorDifferencePercent
ProportionalResize
SafeExec
SafeURLread
SanitizeFilename
ScaleToFitInBox
TranslateWHbyAngle
URLreadFsock
user_function_exists
version_compare_replacement
version_compare_replacement_sub
gd_is_bundled ()
Definition at line 500 of file phpthumb.functions.php.
Referenced by phpUnsharpMask::applyUnsharpMask(), phpthumb_filters::BlurGaussian(), phpthumb_filters::BlurSelective(), phpthumb_filters::Brightness(), phpthumb_filters::Colorize(), phpthumb_filters::Contrast(), phpthumb_filters::EdgeDetect(), phpthumb_filters::Emboss(), phpthumb_filters::Grayscale(), phpthumb::ImageCreateFromStringReplacement(), phpthumb_filters::MeanRemoval(), phpthumb_filters::Negative(), phpthumb_filters::Sepia(), and phpthumb_filters::Smooth().