Senayan3: phpthumb_functions::ImageColorAllocateAlphaSafe
ApacheLookupURIarray
builtin_function_exists
CaseInsensitiveInArray
CleanUpURLencoding
EnsureDirectoryExists
exif_info
filedate_remote
filesize_remote
FunctionIsDisabled
gd_is_bundled
gd_version
GetAllFilesInSubfolders
GetPixelColor
GrayscalePixel
GrayscalePixelRGB
GrayscaleValue
HexCharDisplay
HexColorXOR
ImageColorAllocateAlphaSafe
ImageCopyResampleBicubic
ImageCopyRespectAlpha
ImageCreateFunction
ImageHexColorAllocate
ImageTypeToMIMEtype
IsHexColor
LittleEndian2String
md5_file_safe
nonempty_min
OneOfThese
ParseURLbetter
phpinfo_array
PixelColorDifferencePercent
ProportionalResize
SafeExec
SafeURLread
SanitizeFilename
ScaleToFitInBox
TranslateWHbyAngle
URLreadFsock
user_function_exists
version_compare_replacement
version_compare_replacement_sub
ImageColorAllocateAlphaSafe (&$ gdimg_hexcolorallocate, $ R, $ G, $ B, $ alpha = false)
Definition at line 223 of file phpthumb.functions.php.
References version_compare_replacement().
Referenced by phpthumb_filters::ApplyMask(), phpthumb::CreateGDoutput(), phpthumb_filters::DropShadow(), phpthumb_filters::HistogramOverlay(), phpthumb_filters::HistogramStretch(), phpthumb_filters::ImageBorder(), ImageCopyRespectAlpha(), ImageHexColorAllocate(), phpthumb_filters::Negative(), phpthumb_filters::Sepia(), phpthumb_filters::Threshold(), phpthumb_filters::WatermarkOverlay(), and phpthumb_filters::WhiteBalance().