Senayan3: phpthumb_functions::version_compare_replacement
ApacheLookupURIarray
builtin_function_exists
CaseInsensitiveInArray
CleanUpURLencoding
EnsureDirectoryExists
exif_info
filedate_remote
filesize_remote
FunctionIsDisabled
gd_is_bundled
gd_version
GetAllFilesInSubfolders
GetPixelColor
GrayscalePixel
GrayscalePixelRGB
GrayscaleValue
HexCharDisplay
HexColorXOR
ImageColorAllocateAlphaSafe
ImageCopyResampleBicubic
ImageCopyRespectAlpha
ImageCreateFunction
ImageHexColorAllocate
ImageTypeToMIMEtype
IsHexColor
LittleEndian2String
md5_file_safe
nonempty_min
OneOfThese
ParseURLbetter
phpinfo_array
PixelColorDifferencePercent
ProportionalResize
SafeExec
SafeURLread
SanitizeFilename
ScaleToFitInBox
TranslateWHbyAngle
URLreadFsock
user_function_exists
version_compare_replacement
version_compare_replacement_sub
version_compare_replacement ($ version1, $ version2, $ operator = '')
Definition at line 97 of file phpthumb.functions.php.
References version_compare_replacement_sub().
Referenced by phpthumb_filters::ApplyMask(), phpUnsharpMask::applyUnsharpMask(), phpthumb_filters::BlurGaussian(), phpthumb_filters::BlurSelective(), phpthumb_filters::Brightness(), phpthumb_filters::Colorize(), phpthumb_filters::Contrast(), phpthumb_filters::EdgeDetect(), phpthumb_filters::Emboss(), phpthumb::ErrorImage(), phpthumb::ExtractEXIFgetImageSize(), filedate_remote(), filesize_remote(), phpthumb_filters::Grayscale(), ImageColorAllocateAlphaSafe(), phpthumb::ImageMagickThumbnailToGD(), phpthumb_filters::MeanRemoval(), phpthumb_filters::Negative(), phpthumb::Rotate(), SanitizeFilename(), phpthumb_filters::Sepia(), and phpthumb_filters::Smooth().