Senayan3: phpthumb_functions::ImageCreateFunction
ApacheLookupURIarray
builtin_function_exists
CaseInsensitiveInArray
CleanUpURLencoding
EnsureDirectoryExists
exif_info
filedate_remote
filesize_remote
FunctionIsDisabled
gd_is_bundled
gd_version
GetAllFilesInSubfolders
GetPixelColor
GrayscalePixel
GrayscalePixelRGB
GrayscaleValue
HexCharDisplay
HexColorXOR
ImageColorAllocateAlphaSafe
ImageCopyResampleBicubic
ImageCopyRespectAlpha
ImageCreateFunction
ImageHexColorAllocate
ImageTypeToMIMEtype
IsHexColor
LittleEndian2String
md5_file_safe
nonempty_min
OneOfThese
ParseURLbetter
phpinfo_array
PixelColorDifferencePercent
ProportionalResize
SafeExec
SafeURLread
SanitizeFilename
ScaleToFitInBox
TranslateWHbyAngle
URLreadFsock
user_function_exists
version_compare_replacement
version_compare_replacement_sub
ImageCreateFunction ($ x_size, $ y_size)
Definition at line 361 of file phpthumb.functions.php.
References phpthumb::ErrorImage(), and gd_version().
Referenced by phpthumb::AlphaChannelFlatten(), phpthumb::ApplyFilters(), phpthumb_filters::ApplyMask(), phpthumb::CreateGDoutput(), phpthumb_filters::DropShadow(), phpthumb_filters::Elipse(), phpthumb_filters::Flip(), phpthumb_filters::ImageBorder(), phpthumb_filters::ImprovedImageRotate(), phpthumb_filters::RoundedImageCorners(), phpthumb_filters::WatermarkOverlay(), and phpthumb_filters::WatermarkText().