Senayan3: phpthumb_functions::GetPixelColor
ApacheLookupURIarray
builtin_function_exists
CaseInsensitiveInArray
CleanUpURLencoding
EnsureDirectoryExists
exif_info
filedate_remote
filesize_remote
FunctionIsDisabled
gd_is_bundled
gd_version
GetAllFilesInSubfolders
GetPixelColor
GrayscalePixel
GrayscalePixelRGB
GrayscaleValue
HexCharDisplay
HexColorXOR
ImageColorAllocateAlphaSafe
ImageCopyResampleBicubic
ImageCopyRespectAlpha
ImageCreateFunction
ImageHexColorAllocate
ImageTypeToMIMEtype
IsHexColor
LittleEndian2String
md5_file_safe
nonempty_min
OneOfThese
ParseURLbetter
phpinfo_array
PixelColorDifferencePercent
ProportionalResize
SafeExec
SafeURLread
SanitizeFilename
ScaleToFitInBox
TranslateWHbyAngle
URLreadFsock
user_function_exists
version_compare_replacement
version_compare_replacement_sub
GetPixelColor (&$ img, $ x, $ y)
Definition at line 253 of file phpthumb.functions.php.
Referenced by phpthumb::AlphaChannelFlatten(), phpthumb_filters::ApplyMask(), phpthumb_filters::Brightness(), phpthumb_filters::Colorize(), phpthumb_filters::Contrast(), phpthumb_filters::DropShadow(), phpthumb_bmp::GD2BMPstring(), phpthumb_ico::GD2ICOstring(), phpthumb_filters::HistogramAnalysis(), phpthumb_filters::HistogramStretch(), ImageCopyRespectAlpha(), phpthumb_filters::ImprovedImageRotate(), phpthumb_filters::Negative(), phpthumb_filters::Sepia(), phpthumb_filters::SourceTransparentColorMask(), phpthumb_filters::Threshold(), and phpthumb_filters::WhiteBalance().